[package]
name = "cargo-redox"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
strum = { version = "0.25", features = ["derive"] }
which = "6"
xshell = "0.2"
num_cpus = "1"
